
//version 1.0
public class ftr_addressBean {
    
    public String addressLine1{get;set;}
    public String cityName{get;set;}
    public String state{get;set;}
    public String zipCode{get;set;}
    public Boolean setIncludeFutureFacilityInformation{get;set;}
    public Boolean setIncludeDuplicateFacilityInformation{get;set;}
    public Boolean setRequireUniqueAddress{get;set;}
  //  public String wcCilli{get;set;}
}